services:
  postgres:
    image: postgres:16
    container_name: paymant-postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5434:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    
volumes:
  payment_postgres_data: